#!/bin/bash

PRINT=0

filter="tcp port 80"
if [ $# == 1 ]; then
    filter=$1
fi

# Name of the script that prints out asm for a pred expression
lua_script="pf_pcap_asm.lua"

# Linenumber where the 'execute_pred_ensuring_trace' function is defined
lineno=`grep -n 'function execute_pred_ensuring_trace' $lua_script | cut -d : -f 1`

# Iterate through all asm output but print out only the fragment of asm code for the compiled pred expression
output=`luajit -jdump=m -l pf_pcap_asm -e 'pf_pcap_asm.selftest()'`;
while read -r line; do
    # Was printing and found a blank line
    if [ $PRINT -eq 1 ] && [ -z "$line" ]; then
        break;
    fi
    # Is in printing mode
    if [ $PRINT -eq 1 ]; then
        echo "$line"
        continue;
    fi
    # Found target TRACE, start printing
    matches=$(echo $line | grep "$lua_script:$lineno")
    if [ "$matches" ]; then
        PRINT=1
        echo "$line"
    fi
done <<< "$output"
