#
# This test plan keeps the focus on performance
#
# WARNING: this test plan is heavy!
#
# It requires long time runs and several GB on disk. It is used to benchmark mainly
#
# Test cases added here should look for variables impacting performance. Those
# variables are usually related to number of lines/code generated by filter (heavy
# filters), number of packets per trace, etc)
#
# Set 'enabled' to 'false' in order to skip test cases while hacking
#
# Use "make test | grep 'tc id'" to identify test cases failing quickly
#
# i.e:
#  $ make test | grep 'tc id'
#  tc id 1 FAIL (48 != 47)
#  tc id 2 PASS
#  tc id 3 SKIP
#  ...
#
# Before enabling those tests you must uncompress the proper pcaps
#
# WARNING: one-gigabyte.pcap.xz will expand from 10MB to 1GB and so on! :)
#
# $ unxz src/ts/tests/one-gigabyte.pcap.xz
#

id:1
description:1 GB test - baseline
filter:
pcap_file:igalia/one-gigabyte.pcap
expected_result:1166716
enabled:true

id:2
description:1 GB test - ip
filter: ip
pcap_file:igalia/one-gigabyte.pcap
expected_result:1166716
enabled:true
